update

diff --git a/c_git b/c_git
--- a/c_git
+++ b/c_git
@@ -22,68 +22,59 @@ else
     then
         #No git versionning
         git init
-    else
+    fi
+    remote_line=$( git remote -v | wc -l )
     
-        remote_line=$( git remote -v | wc -l )
+    if [ "$remote_line" -gt 2 ] 
+    then
+        # Too much remote
+        echo "To much remote, you have to deal with this manually!"
+        exit(1)
+    elif [ "$remote_line" -eq 0 ]
+    then
+        # No remote 
+        curl -u 'bam241' https://api.github.com/user/repos -d '{"name":"'${PWD##*/}'"}'
+        git remote add origin git@github.com:bam241/${PWD##*/}.git
+        git-change-url --to-ssh
+    elif [ "$remote_line" -eq 2 ] 
+    then
+        # Only one remote: analysing the remote
+        remote=$( git remote -v| grep push |cut -f2 |cut -d' ' -f1 )
+        r_name=$( git remote -v |grep push |cut -f1 )
         
-        if [ "$remote_line" -gt 2 ] 
+        if [[ $remote =~ git ]] 
         then
-            # Too much remote
-            echo "To much remote, you have to deal with this manually!"
+            # Remote with ssh url
+            r_user=$( echo $remote |cut -d":" -f2 |cut -d"/" -f1 )
+            r_project=$( echo $remote |cut -d":" -f2 |cut -d"/" -f2 )
+        elif [ ${remote} =~ https\:\/\/ ]
+        then
+            # Remote with https url
+            r_user=$( echo ${remote} | cut -d"/" -f4 )
+            r_project=$( echo ${remote} | cut -d"/" -f5 )
+        else
+            # Un-reconized url
+            echo "Unable to read the remote... please procced manually!!"
             exit(1)
-
-        elif [ "$remote_line" -eq 0 ]
-        then
-            # No remote 
-            curl -u 'bam241' https://api.github.com/user/repos -d '{"name":"'${PWD##*/}'"}'
-            git remote add origin git@github.com:bam241/${PWD##*/}.git
-            git-change-url --to-ssh
-        
-        elif [ "$remote_line" -eq 2 ] 
-        then
-            # Only one remote: analysing the remote
-            remote=$( git remote -v| grep push |cut -f2 |cut -d' ' -f1 )
-            r_name=$( git remote -v |grep push |cut -f1 )
-            
-            if [[ $remote =~ git ]] 
-            then
-                # Remote with ssh url
-                r_user=$( echo $remote |cut -d":" -f2 |cut -d"/" -f1 )
-                r_project=$( echo $remote |cut -d":" -f2 |cut -d"/" -f2 )
-                 
-            elif [ ${remote} =~ https\:\/\/ ]
-            then
-                # Remote with https url
-                r_user=$( echo ${remote} | cut -d"/" -f4 )
-                r_project=$( echo ${remote} | cut -d"/" -f5 )
-            
-            else
-                # Un-reconized url
-                echo "Unable to read the remote... please procced manually!!"
-                exit(1)
-            
-            fi
-            
-
-            if [[ "$user" == "$r_user" ]]
-            then
-                # User already own the remote...
-                echo "Origin pointing to your fork/repo, nothing to do..."
-                exit(0)
-            fi
-            
-            if [[ $r_project =~ '.git'  ]]
-            then
-                r_project=${r_project: : -4}
-            fi
-            
-            # cFork the repo then setup the origin/upstream remotes
-            curl -X POST -u "$user" "https://api.github.com/repos/$r_user/$r_project/forks"
-            [ $? = 0 ] || abort "fork failed"
-            git remote rm $r_name
-            git remote add origin git@github.com:$user/$r_project
-            git remote add upstream git@github.com:$r_user/$r_project
-        
         fi
+
+        if [[ "$user" == "$r_user" ]]
+        then
+            # User already own the remote...
+            echo "Origin pointing to your fork/repo, nothing to do..."
+            exit(0)
+        fi
+        
+        if [[ $r_project =~ '.git'  ]]
+        then
+            r_project=${r_project: : -4}
+        fi
+        
+        # cFork the repo then setup the origin/upstream remotes
+        curl -X POST -u "$user" "https://api.github.com/repos/$r_user/$r_project/forks"
+        [ $? = 0 ] || abort "fork failed"
+        git remote rm $r_name
+        git remote add origin git@github.com:$user/$r_project
+        git remote add upstream git@github.com:$r_user/$r_project
     fi
 fi
